GET {{url}}/posts/{{id}}/
Accept: application/json

###
DELETE {{url}}/posts/{{id}}/
Accept: application/json

###
PUT {{url}}/posts/{{id}}/
Content-Type: application/json

{
  "title": "Job classes in Final Fantasy updated",
  "content": "This article explains the job classes in Final Fantasy updated.",
  "category": "Jobs updated",
  "tags": [
    "Final",
    "Fantasy",
    "Jobs",
    "Updated"
  ]
}

###
POST {{url}}/posts/
Content-Type: application/json

{
  "title": "Job classes in Final Fantasy",
  "content": "This article explains the job classes in Final Fantasy.",
  "category": "Jobs",
  "tags": [
    "Final",
    "Fantasy",
    "Jobs"
  ]
}

###
